Merge common init script

diff --git a/bin/rebuild b/bin/rebuild
--- a/bin/rebuild
+++ b/bin/rebuild
@@ -6,6 +6,16 @@
 
 # Build composer, build theme, etc.
 bin/build
+retVal=$?
+if [ $retVal -ne 0 ]; then
+  # Exit if build failed.
+  exit $retVal
+fi
 
 # Run updates, clear cache, etc.
 bin/import
+retVal=$?
+if [ $retVal -ne 0 ]; then
+  # Exit if import/install failed.
+  exit $retVal
+fi
