Add some echo statements

diff --git a/bin/git/mr b/bin/git/mr
--- a/bin/git/mr
+++ b/bin/git/mr
@@ -16,6 +16,11 @@ LAB="docker run -it --rm -v ${HOME}:/root -v ${GITDIR}:/home/git outrigger/lab"
 
 read -p "Merge Request summary?  " varDesc
 
+if [ -z ${varDesc} ]; then
+  echo "No summary given, aborting."
+  exit 1
+fi
+
 FEATURE_BRANCH="$(git symbolic-ref HEAD 2>/dev/null)"
 ISSUE_NUM="${FEATURE_BRANCH//[!0-9]/}"
 
@@ -28,7 +33,9 @@ DEVELOP_BRANCH=${DEVELOP_BRANCH:-develop}
 MASTER_UPPER=$(echo ${MASTER_BRANCH} | tr '[:lower:]' '[:upper:]')
 DEVELOP_UPPER=$(echo ${DEVELOP_BRANCH} | tr '[:lower:]' '[:upper:]')
 
+echo "Creating MR for $DEVELOP_UPPER..."
 lab mr create origin $DEVELOP_BRANCH -l $DEVELOP_BRANCH -m "$DEVELOP_UPPER:: $JIRA_NAME$ISSUE_NUM: $varDesc"
+echo "Creating MR for $MASTER_UPPER..."
 lab mr create origin $MASTER_BRANCH -l $MASTER_BRANCH -m "$MASTER_UPPER:: $JIRA_NAME$ISSUE_NUM: $varDesc"
 
 
